[package]
name = "real-world-cryptography"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
	"chapter-2",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
